
site_name: AllenArticles
site_description: 湖南省零檬信息技术有限公司-allen老师个人技术博客
site_author: allen
copyright: © Copyright 湖南省零檬信息技术有限公司-allen老师 2019-2020

nav:
        - Home: 'README.md'
        - jmeter:
                - '环境安装': 'jmeter环境安装.md'
                - '提取列表最后一个值': 'Jmeter不写代码，秒秒钟提取动态列表最后一个值.md'
                - '不写代码搞定结果中文': '不写代码搞定jmeter响应结果中文乱码.md'
                - '最新版写soap接口': '最新版jmeter写soap协议接口请求.md'
                - '跨平台读取csv文件设置': 'jmeter跨平台csv文件路径该如何设置.md'
                - '跨线程组取参': 'jmeter跨线程组取参数的两种方法.md'
                - 'jsonpath的用法': 'jmeter鲜为人知的jsonpath用法.md'
                - '登录一次性能测试': 'jmeter性能测试只想登录一次怎么做.md'
                - '根据事务生成报告': 'jmeter根据事务生成报告.md'
                - '随机用户注册登录及之后操作': '完全随机用户注册，如何继续完成登录及之后操作.md'
                - '临界部分控制器使用': 'critical section controller(临界部分控制器)到底该如何用.md'
                - '如何使用接口返回的多值': 'jmeter如何使用接口返回的多值.md'
                - 'jmeter也撒谎': 'jmeter撒的慌你可能已经信以为真了.md'
                - '不写代码jmeter结果写入execl': '不写java代码把jmeter结果写入excel表格.md'
                - '用jmeter的GUI生成报告': '图形界面Jmeter也能生成html报告，你知道吗？.md'
        - robotframework:
                - 'linux+python3+RIDE安装': 'RIDE可以在linux+python3的环境中运行啦！.md'

theme: readthedocs


