
site_name: AllenArticles
site_description: 湖南省零檬信息技术有限公司-allen老师个人技术博客
site_author: allen
copyright: © Copyright 湖南省零檬信息技术有限公司-allen老师 2019-2020

nav:
        - Home: 'README.md'
        - jmeter:
                - '环境安装': 'jmeter环境安装.md'
                - '用jar包启动jmeter': '用jar包启动jmeter.md'
                - '提取列表最后一个值': 'Jmeter不写代码，秒秒钟提取动态列表最后一个值.md'
                - '不写代码搞定结果中文': '不写代码搞定jmeter响应结果中文乱码.md'
                - '最新版写soap接口': '最新版jmeter写soap协议接口请求.md'
                - '跨平台读取csv文件设置': 'jmeter跨平台csv文件路径该如何设置.md'
                - '跨线程组取参': 'jmeter跨线程组取参数的两种方法.md'
                - 'jsonpath的用法': 'jmeter鲜为人知的jsonpath用法.md'
                - '登录一次性能测试': 'jmeter性能测试只想登录一次怎么做.md'
                - '根据事务生成报告': 'jmeter根据事务生成报告.md'
                - '随机用户注册登录及之后操作': '完全随机用户注册，如何继续完成登录及之后操作.md'
                - '临界部分控制器使用': 'critical section controller(临界部分控制器)到底该如何用.md'
                - '如何使用接口返回的多值': 'jmeter如何使用接口返回的多值.md'
                - 'jmeter也撒谎': 'jmeter撒的慌你可能已经信以为真了.md'
                - '不写代码jmeter结果写入execl': '不写java代码把jmeter结果写入excel表格.md'
                - '用jmeter的GUI生成报告': '图形界面Jmeter也能生成html报告，你知道吗？.md'
                - '一个正则提取器提取多个值': 'jmeter用一个正则提取器一次提取多个值的应用.md'
                - 'jpgc无法下载问题解决办法': 'Jmeter插件jpgc无法下载安装问题解决办法.md'
                - 'jdbc数据的四种使用方法': 'jmeter获取jdbc数据使用的四种方法.md'
                - 'jmeter混合场景如何设计': 'Jmeter性能测试时如何设计混合场景.md'
                - 'jmeter如何测试websocket接口': 'jmeter如何测试websocket接口.md'
                - 'MQTT协议如何测试': 'Jmeter如何测试MQTT服务.md'
                - 'TPS上不去，分析思路': '性能测试TPS上不去问题分析，思路整理.md'
                - 'jmeter面试题剖析实战': '一个jmeter面试题.md'
                - 'jmeter面向目标的性能场景设计': 'jmeter面向目标的性能场景设计.md'
                - '网络性能瓶颈分析': '网络性能瓶颈分析，看这篇就够了.md'
                - '5个前端性能测试工具': '前端性能测试工具.md'
                - 'jmeter时间相关转换': 'Jmeter如何把时间戳转为本地时间.md'
                - '写爬虫，其实不需要懂代码': '写爬虫，要懂代码吗？No.md'
        - 其他知识:
                - '性能工具合集': '性能工具合集.md'
                - 'JDK_HotSpot特性讲解': 'JDK_HotSpot特性讲解.md'
                - 'jmap用法': 'jmap用法.md'
                - '常用软件安装合集': '常用软件安装合集.md'
                - 'proc文件解读': 'proc文件解读.md'
                - 'mysql主从数据库': '快速搭建mysql主从数据库.md'
                - 'sysctl网络知识': 'sysctl网络相关配置.md'
        - locust:
                  - 'locut入门': 'locust入门.md'
                  - 'locust的1时代入门': 'locust的‘1’版本时代入门.md'
        - ngrinder:
                  - '快速写出ngrinder脚本': 'ngrinder入门.md'
        - zabbix:
                  - 'zabbix监控介绍': 'zabbix入门介绍.md'
                  - 'centos8安装zabbix5': '在centos8中安装zabbix5.0.md'
                  - 'centos7搭建zabbix5.0': 'centos7+zabbix5.0+nginx+mysql安装方法.md'
                  - 'zabbix添加监控机器': 'zabbix管理界面添加监控机器.md'
                  - '用zabbix监控被测linux服务器资源': 'centos系统增加zabbix资源监控.md'
                  - 'zabbix监控模板配置': 'zabbix 监控模板配置.md'
                  - 'zabbix与grafana结合，实现服务器监控': 'zabbix与grafana结合，监控性能测试服务器.md'
                  - 'prometheus资源监控': 'prometheus监控服务器.md'
                  - 'zabbix与prometheus比较': 'zabbix与prometheus比较.md'
        - gra-prometheus:
            - '用docker搭建grafana+influxdb监控平台': 'docker方式搭建grafana+influxdb监控平台.md'
            - 'prometheus语法': 'prometheus语法.md'
            - 'prometheus监控硬件资源': 'grafana+prometheus监控服务器硬件资源.md'
            - 'prometheus监控tomcat': 'grafana+prometheus+tomcat监控.md'
            - 'prometheus监控nginx': 'grafana+prometheus+nginx监控负载均衡.md'
            - 'prometheus监控mysql': 'grafana+prometheus+mysql 监控关系型数据库.md'
            - 'prometheus监控redis': 'grafana+prometheus+redis 监控缓存数据库.md'
        - 性能监控:
            - '自制一个最简单的监控平台': '一行命令，自制一个服务器监控平台.md'
            - 'nmon最详尽的用法介绍': '一文让你学到nmon最详尽的用法.md'
        - 其他性能工具:
                  - 'wrk基准测试技能介绍': 'wrk基准测试技能介绍.md'
                  - 'ab做性能测试': '一文告诉你ab如何做性能测试.md'
        - 自动化:
                - 'linux+python3+RIDE安装': 'RIDE可以在linux+python3的环境中运行啦！.md'
                - 'RIDE中文乱码解决办法与剖析': 'RIDE1.7.4.1版本中文乱码问题解决办法.md'
                - 'Docker搭建jenkins部署python3界面自动化': '使用Docker搭建Jenkins部署python3项目.md'

theme: readthedocs


