
site_name: AllenArticles
site_description: 湖南省零檬信息技术有限公司-allen老师个人技术博客
site_author: allen
copyright: © Copyright 湖南省零檬信息技术有限公司-allen老师 2019-2020

nav:
        - Home: 'README.md'
        - jmeter:
                - '环境安装': 'jmeter环境安装.md'
                - '用jar包启动jmeter': '用jar包启动jmeter.md'
                - '提取列表最后一个值': 'Jmeter不写代码，秒秒钟提取动态列表最后一个值.md'
                - '不写代码搞定结果中文': '不写代码搞定jmeter响应结果中文乱码.md'
                - '最新版写soap接口': '最新版jmeter写soap协议接口请求.md'
                - '跨平台读取csv文件设置': 'jmeter跨平台csv文件路径该如何设置.md'
                - '跨线程组取参': 'jmeter跨线程组取参数的两种方法.md'
                - 'jsonpath的用法': 'jmeter鲜为人知的jsonpath用法.md'
                - '登录一次性能测试': 'jmeter性能测试只想登录一次怎么做.md'
                - '根据事务生成报告': 'jmeter根据事务生成报告.md'
                - '随机用户注册登录及之后操作': '完全随机用户注册，如何继续完成登录及之后操作.md'
                - '临界部分控制器使用': 'critical section controller(临界部分控制器)到底该如何用.md'
                - '如何使用接口返回的多值': 'jmeter如何使用接口返回的多值.md'
                - 'jmeter也撒谎': 'jmeter撒的慌你可能已经信以为真了.md'
                - '不写代码jmeter结果写入execl': '不写java代码把jmeter结果写入excel表格.md'
                - '用jmeter的GUI生成报告': '图形界面Jmeter也能生成html报告，你知道吗？.md'
                - '一个正则提取器提取多个值': 'jmeter用一个正则提取器一次提取多个值的应用.md'
                - 'jpgc无法下载问题解决办法': 'Jmeter插件jpgc无法下载安装问题解决办法.md'
                - 'jdbc数据的四种使用方法': 'jmeter获取jdbc数据使用的四种方法.md'
                - 'jmeter混合场景如何设计': 'Jmeter性能测试时如何设计混合场景.md'
                - 'jmeter如何测试websocket接口': 'jmeter如何测试websocket接口.md'
                - '自制一个最简单的监控平台': '一行命令，自制一个服务器监控平台.md'
                - 'MQTT协议如何测试': 'Jmeter如何测试MQTT服务.md'
                - 'TPS上不去，分析思路': '性能测试TPS上不去问题分析，思路整理.md'
                - '用docker搭建grafana+influxdb监控平台': 'docker方式搭建grafana+influxdb监控平台.md'
                - 'jmeter面试题剖析实战': '一个jmeter面试题.md'
                - 'jmeter面向目标的性能场景设计': 'jmeter面向目标的性能场景设计.md'
        - locust:
                  - 'locut入门': 'locust入门.md'
                  - 'locust的1时代入门': 'locust的‘1’版本时代入门.md'
        - ngrinder:
                  - '快速写出ngrinder脚本': 'ngrinder入门.md'
        + 其他工具:
                  - 'wrk基准测试技能介绍': 'wrk基准测试技能介绍.md'
                  - 'ab做性能测试': '一文告诉你ab如何做性能测试.md'
        + robotframework:
                - 'linux+python3+RIDE安装': 'RIDE可以在linux+python3的环境中运行啦！.md'
                - 'RIDE中文乱码解决办法与剖析': 'RIDE1.7.4.1版本中文乱码问题解决办法.md'

theme: readthedocs


